name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge
          conda-remove-defaults: "true"
          environment-file: environment.yml
      - name: Notebooks
        shell: bash -l {0}
        timeout-minutes: 15
        env:
          MPLBACKEND: Agg
        run: |
          conda install -y papermill
          papermill 0-python.ipynb 0-python-out.ipynb -k python3
          papermill 1-executorlib.ipynb 1-executorlib-out.ipynb -k python3
          papermill 2-pyiron_workflow.ipynb 2-pyiron_workflow-out.ipynb -k python3
          papermill 3-pyironflow.ipynb 3-pyironflow-out.ipynb -k python3
